name: Josh Asch
author: Josh Asch
description: "The random ramblings of Josh Asch, a Computer Science student from the UK."
url: "http://joshasch.com"

permalink: /:year/:month/:day/:title/

twitter_handle: josh_asch
email: josh@joshasch.com

highlighter: rouge

paginate: 5
paginate_path: "page/:num"
