name: Liv Asch
author: Liv Asch
description: "The random ramblings of Liv Asch, a software engineer from the UK."
url: "http://bearhat.co.uk"

permalink: /:year/:month/:day/:title/

twitter_handle: jobbogamer
email: olivia@bearhat.co.uk

paginate: 5
paginate_path: "page/:num"
