name: Josh Asch
author: Josh Asch
description: "The random ramblings of Josh Asch, a Computer Science student from the UK."
url: "http://joshasch.com"

permalink: /:year/:month/:day/:title/

twitter_handle: jobbogamer
email: josh@joshasch.com

pygments: true

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

paginate: 5
paginate_path: "page/:num"